### ISSUE TITLE
The used version of vm2 is vulnerable

### ISSUE THREAD

**Issue by sbrunner** [eight04/node_vm2#122]
https://github.com/eight04/node_vm2/blob/master/node_vm2/vm-server/package-lock.json#L1252

See: https://security.snyk.io/vuln/SNYK-JS-VM2-5537100

Thanks to updating it and creating a new release :-)

**Comment by eight04** [comment]
Since vm2 is discontinued, I think we should

1. Upgrade vm2 to the latest version.
2. Release the final version.
3. Probably deprecate node_vm2?

**Comment by sbrunner** [comment]
OK, thanks for the info :-)

**Comment by sbrunner** [comment]
Thanks :-)
