### ISSUE TITLE
Using built-in module

### ISSUE THREAD

**Issue by ryuneeee** [eight04/node_vm2#2]
Hello,
I'm interesting this project for using python chatbot. And, very thanks porting to python.
https://github.com/patriksimek/vm2#quick-example
partiksimek's vm2 support node's built-in require module with options.

I trying this feature. but, can't using built-in require module. How I can this?

Code
-----
```javascript
with VM(timeout=2000, require='{external:true'}) as vm:
    vm.run(recv_message)
```

Result
-----
`require is not defined`

Thanks.

**Comment by eight04** [comment]
You have to use `NodeVM`, [the doc](https://github.com/patriksimek/vm2#nodevm).

An example which requires builtin `os` module:
```python
from node_vm2 import NodeVM

script = """
const os = require("os");
console.log(os.platform(), os.arch(), os.release());
"""

with NodeVM(require={"builtin": ["os"]}) as vm:
	vm.run(script)

```

**Comment by ryuneeee** [comment]
OMG! I understand now, vm and NodeVM are so different. thanks :)
